---
title: "TEAMWORK.md"
author: "Suhaila Ng"
date: "2026-09-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Division of Labour
How will you divide the work required for this milestone? Read through the project and figure out who does what tasks/exercises. Be as specific as possible.

Suhaila: Creates Teamwork Charter markdown file + is "a different person" in 5.4 + Teammate A + all do tidying up in 7 + submission (8)

Courtney: Creates README + is "a different person" in 3.6 + Teammate B + all do tidying up in 7

Spenser: Elevating the Teamwork Contract and README + is a "different person in 4.4 + Teammate C + all do tidying up in 7


Timing
When will you each aim to submit your pull requests, keeping in mind that another teammate will need to review your work? Warning: Do not submit your part of the project last-minute. Your teammate’s review of your work may not be trivial: if there are errors, your team will need time to debug them.
We will aim to be done by Tuesday so we can check that everything is great and tidy up during the class.


Communication
How will you communicate with each other? For example, will you be using both Slack and GitHub Issues? For what, exactly? How long will it realistically take you to respond to a message? Will you hold a regular meeting, or rely exclusively on asynchronous communication?

We will use our Whatsapp groupchat. We will respond within 24 hours. We will check in during next Tuesday's in-person class to see where we are at. In the meantime, we will message our progress on the groupchat.